import React, { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { fetchProducts, resetProductState } from '../../features/products/productSlice';
import { createSaleThunk } from '../../features/sales/saleSlice';
import Layout from '../../layouts/MainLayout';

const SaleFormModal = ({ isOpen, onClose, onSubmit, sale, isEditing }) => {
    const dispatch = useDispatch();
    const { token } = useSelector((state) => state.auth);
    const { products: productList, status: productsStatus, error: productsError } = useSelector((state) => state.products);
    const { status: saleStatus } = useSelector((state) => state.sales);

    const [cart, setCart] = useState([]);
    const [customerName, setCustomerName] = useState('');
    const [paymentMethod, setPaymentMethod] = useState('CASH');
    const [paymentStatus, setPaymentStatus] = useState('PENDING');
    // Taxes, discounts, etc. would also be managed here

    useEffect(() => {
        if (!productList || productList.length === 0) {
            dispatch(fetchProducts({ token, params: { limit: 1000 } })); // Fetch products for POS selection
        }
    }, [dispatch, token, productList]);

    // Effect to reset form when modal opens/closes or isEditing state changes
    useEffect(() => {
        if (isOpen) {
            if (sale && isEditing) {
                // Populate form with sale metadata if editing (e.g., payment status)
                setCustomerName(sale.customerName || '');
                setPaymentMethod(sale.paymentMethod || 'CASH');
                setPaymentStatus(sale.paymentStatus || 'PENDING');
            } else {
                // Reset for new sale creation
                setCustomerName('');
                setPaymentMethod('CASH');
                setPaymentStatus('PENDING');
                setCart([]); // Clear cart for new sale
            }
        } else {
            // Clear state when modal closes
            setCart([]);
            setCurrentSale(null);
            dispatch(resetSaleState()); // Clear sale-related state if needed
        }
    }, [isOpen, sale, isEditing, dispatch]);

    const handleProductSelect = (e) => {
        const productId = e.target.value;
        if (!productId) return;
        const selectedProduct = productList.find(p => p._id === productId);
        if (selectedProduct) {
            // Add to cart if not already there, or update quantity
            const existingItemIndex = cart.findIndex(item => item.productId === productId);
            if (existingItemIndex > -1) {
                const newCart = [...cart];
                newCart[existingItemIndex].quantity++;
                newCart[existingItemIndex].totalPrice = newCart[existingItemIndex].quantity * newCart[existingItemIndex].sellingPrice;
                setCart(newCart);
            } else {
                setCart([...cart, {
                    productId: selectedProduct._id,
                    name: selectedProduct.name, // For display in cart
                    sku: selectedProduct.sku,     // For display in cart
                    sellingPrice: selectedProduct.sellingPrice,
                    quantity: 1,
                    totalPrice: selectedProduct.sellingPrice,
                }]);
            }
        }
    };

    const handleQuantityChange = (productId, quantity) => {
        const newCart = cart.map(item => {
            if (item.productId === productId) {
                const newQuantity = parseInt(quantity);
                return {
                    ...item,
                    quantity: newQuantity,
                    totalPrice: newQuantity * item.sellingPrice
                };
            }
            return item;
        }).filter(item => item.quantity > 0); // Remove items with 0 quantity
        setCart(newCart);
    };

    const handleRemoveItem = (productId) => {
        setCart(cart.filter(item => item.productId !== productId));
    };

    // Calculate totals dynamically
    const subtotal = cart.reduce((sum, item) => sum + item.totalPrice, 0);
    // Add tax and discount logic here based on shop settings or user input
    const taxAmount = subtotal * 0.1; // Example: 10% tax
    const discount = 0; // Example: no discount
    const totalAmount = subtotal + taxAmount - discount;

    const handleFinalSubmit = () => {
        // Construct the sale data object
        const saleData = {
            products: cart,
            customerName: customerName,
            paymentMethod: paymentMethod,
            paymentStatus: paymentStatus,
            taxAmount: taxAmount,
            discount: discount,
            // totalAmount is calculated by backend, but we can send it too
            totalAmount: totalAmount,
            // receiptNumber is generated by backend
        };
        onSubmit(saleData); // Pass to parent handler (usually for create)
    };

    return (
        <div className={isOpen ? "fixed inset-0 z-50 overflow-y-auto bg-black bg-opacity-50 flex items-center justify-center p-4" : "hidden"}>
            <div className="relative bg-white rounded-lg shadow-xl max-w-4xl w-full">
                <div className="flex justify-between items-center p-4 border-b">
                    <h3 className="text-xl font-semibold text-gray-900">{isEditing ? 'Sale Details' : 'New Sale (POS)'}</h3>
                    <button onClick={onClose} className="text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-gray-500 rounded-full p-1">
                        <svg className="h-6 w-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12"></path></svg>
                    </button>
                </div>
                <div className="p-6">
                    {!isEditing && (
                        <div className="mb-6">
                            <label htmlFor="productSelect" className="block text-sm font-medium text-gray-700">Add Product</label>
                            <select
                                id="productSelect"
                                onChange={handleProductSelect}
                                className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                            >
                                <option value="">Select Product</option>
                                {productsStatus === 'loading' && <option disabled>Loading products...</option>}
                                {productsStatus === 'failed' && <option disabled>Error loading products</option>}
                                {products?.map(prod => (
                                    <option key={prod._id} value={prod._id}>
                                        {prod.name} (SKU: {prod.sku}) - Stock: {prod.stockQuantity}
                                    </option>
                                ))}
                            </select>
                            {productsError && <p className="text-red-500 text-xs mt-1">{productsError}</p>}
                        </div>
                    )}

                    {/* Cart Display */}
                    <div className="min-h-[200px] max-h-[400px] overflow-y-auto border rounded-md mb-6 p-4">
                        {cart.length === 0 ? (
                            <p className="text-center text-gray-500">Your cart is empty. Add products to start a sale.</p>
                        ) : (
                            <ul className="space-y-3">
                                {cart.map(item => (
                                    <li key={item.productId} className="flex justify-between items-center p-3 border-b last:border-b-0">
                                        <div>
                                            <p className="font-medium">{item.name} ({item.sku})</p>
                                            <p className="text-sm text-gray-600">Price: ${item.sellingPrice.toFixed(2)}</p>
                                        </div>
                                        <div className="flex items-center space-x-2">
                                            <input
                                                type="number"
                                                min="1"
                                                value={item.quantity}
                                                onChange={(e) => handleQuantityChange(item.productId, e.target.value)}
                                                className="w-16 text-center border border-gray-300 rounded-md p-1"
                                            />
                                            <span>x ${item.totalPrice.toFixed(2)}</span>
                                            <button onClick={() => handleRemoveItem(item.productId)} className="text-red-500 hover:text-red-700">X</button>
                                        </div>
                                    </li>
                                ))}
                            </ul>
                        )}
                    </div>

                    {/* Sale Summary and Customer Info */}
                    <div className="mt-4 flex flex-col md:flex-row gap-6">
                        {/* Customer Info & Payment Details */}
                        <div className="md:w-1/2 space-y-4">
                            <FormInput label="Customer Name" name="customerName" value={customerName} onChange={(e) => setCustomerName(e.target.value)} />
                            
                            <div>
                                <label htmlFor="paymentMethod" className="block text-sm font-medium text-gray-700">Payment Method</label>
                                <select
                                    id="paymentMethod"
                                    name="paymentMethod"
                                    value={paymentMethod}
                                    onChange={(e) => setPaymentMethod(e.target.value)}
                                    className="mt-1 block w-full pl-3 pr-10 py-2 border border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                                >
                                    <option value="CASH">Cash</option>
                                    <option value="CARD">Card</option>
                                    <option value="ONLINE">Online</option>
                                </select>
                            </div>
                            {!isEditing && (
                                <div>
                                    <label htmlFor="paymentStatus" className="block text-sm font-medium text-gray-700">Payment Status</label>
                                    <select
                                        id="paymentStatus"
                                        name="paymentStatus"
                                        value={paymentStatus}
                                        onChange={(e) => setPaymentStatus(e.target.value)}
                                        className="mt-1 block w-full pl-3 pr-10 py-2 border border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md"
                                    >
                                        <option value="PENDING">Pending</option>
                                        <option value="PAID">Paid</option>
                                        <option value="FAILED">Failed</option>
                                    </select>
                                </div>
                            )}
                        </div>

                        {/* Totals Summary */}
                        <div className="md:w-1/2 border-l-2 border-gray-200 pl-4">
                            <div className="flex justify-between mb-2">
                                <span className="text-gray-700">Subtotal:</span>
                                <span className="font-semibold">${subtotal.toFixed(2)}</span>
                            </div>
                            <div className="flex justify-between mb-2">
                                <span className="text-gray-700">Tax ({ (taxAmount / (subtotal || 1) * 100).toFixed(1)}%):</span>
                                <span className="font-semibold">${taxAmount.toFixed(2)}</span>
                            </div>
                            <div className="flex justify-between mb-4">
                                <span className="text-gray-700">Discount:</span>
                                <span className="font-semibold">-${discount.toFixed(2)}</span>
                            </div>
                            <div className="flex justify-between border-t pt-4">
                                <span className="text-xl font-bold text-gray-900">Total:</span>
                                <span className="text-xl font-bold text-indigo-600">${totalAmount.toFixed(2)}</span>
                            </div>
                        </div>
                    </div>
                </div>

                <div className="flex justify-end space-x-3 mt-8">
                    <button type="button" onClick={onClose} className="px-6 py-3 text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 focus:outline-none">Cancel</button>
                    {!isEditing && (
                        <button
                            onClick={handleFinalSubmit} // For creating a new sale
                            disabled={cart.length === 0 || saleStatus === 'loading' || totalAmount === 0} // Disable if cart empty or loading
                            className="px-6 py-3 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-opacity-50 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            {saleStatus === 'loading' ? 'Processing...' : 'Complete Sale'}
                        </button>
                    )}
                    {/* Add an update button for metadata edits if needed */}
                </div>
            </div>
        </div>
    );
};

export default SaleFormModal;
